import type { Habit } from "../types/checkpoint";

export const seedHabits: Habit[] = [
  {
    id: "wake-up-early",
    name: "Wake up early",
    icon: "◷",
    category: "morning",
    mode: "checkbox",
    order: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: "exercise-run",
    name: "Exercise/Run",
    icon: "⌁",
    category: "morning",
    mode: "checkbox",
    order: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: "study",
    name: "Study",
    icon: "▰",
    category: "day",
    mode: "checkbox",
    order: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: "content-creation",
    name: "Content creation",
    icon: "▸",
    category: "day",
    mode: "checkbox",
    order: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: "water",
    name: "2L water",
    icon: "♙",
    category: "day",
    mode: "checkbox",
    order: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: "no-junk",
    name: "No junk",
    icon: "✦",
    category: "day",
    mode: "checkbox",
    order: 6,
    createdAt: new Date().toISOString(),
  },
  {
    id: "read-book",
    name: "Read book",
    icon: "▤",
    category: "night",
    mode: "checkbox",
    order: 7,
    createdAt: new Date().toISOString(),
  },
  {
    id: "plan",
    name: "Plan",
    icon: "☷",
    category: "night",
    mode: "checkbox",
    order: 8,
    createdAt: new Date().toISOString(),
  },
  {
    id: "journal",
    name: "Journal",
    icon: "▤",
    category: "night",
    mode: "checkbox",
    order: 9,
    createdAt: new Date().toISOString(),
  },
];
